version: '3'
services:
  db:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  web:
    image: nginx
    container_name: ${COMPOSE_PROJECT_NAME}_webserver
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data:
