version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: webserver
    ports:
      - "8080:80"        # Map port 8080 on host to port 80 in the container
    volumes:
      - ./html:/usr/share/nginx/html  # Mount local html directory to Nginx web directory
    networks:
      - webnet            # Connect the web service to the 'webnet' network

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
    networks:
      - webnet            # Connect the db service to the 'webnet' network

networks:
  webnet:
    driver: bridge         # Define a custom network for the services to communicate

volumes:
  db_data:                 # Create a named volume for MySQL data persistence
